site_name: Dao De Jing
theme:
  name: 'material'
  custom_dir: 'overrides'
markdown_extensions:
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Chapters:
      - Chapter 1: chapters/01.md
      - Chapter 2: chapters/02.md
      - Chapter 3: chapters/03.md
      - Chapter 4: chapters/04.md
      - Chapter 5: chapters/05.md
      - Chapter 6: chapters/06.md
      - Chapter 7: chapters/07.md
      - Chapter 8: chapters/08.md
      - Chapter 9: chapters/09.md
      - Chapter 10: chapters/10.md
      - Chapter 11: chapters/11.md
      - Chapter 12: chapters/12.md
      - Chapter 13: chapters/13.md
      - Chapter 14: chapters/14.md
      - Chapter 15: chapters/15.md
      - Chapter 16: chapters/16.md
      - Chapter 17: chapters/17.md
      - Chapter 18: chapters/18.md
      - Chapter 19: chapters/19.md
      - Chapter 20: chapters/20.md
      - Chapter 21: chapters/21.md
      - Chapter 22: chapters/22.md
      - Chapter 23: chapters/23.md
      - Chapter 24: chapters/24.md
      - Chapter 25: chapters/25.md
      - Chapter 26: chapters/26.md
      - Chapter 27: chapters/27.md
      - Chapter 28: chapters/28.md
      - Chapter 29: chapters/29.md
      - Chapter 30: chapters/30.md
      - Chapter 31: chapters/31.md
      - Chapter 32: chapters/32.md
      - Chapter 33: chapters/33.md
      - Chapter 34: chapters/34.md
      - Chapter 35: chapters/35.md
      - Chapter 36: chapters/36.md
      - Chapter 37: chapters/37.md
      - Chapter 38: chapters/38.md
      - Chapter 39: chapters/39.md
      - Chapter 40: chapters/40.md
      - Chapter 41: chapters/41.md
      - Chapter 42: chapters/42.md
      - Chapter 43: chapters/43.md
      - Chapter 44: chapters/44.md
      - Chapter 45: chapters/45.md
      - Chapter 46: chapters/46.md
      - Chapter 47: chapters/47.md
      - Chapter 48: chapters/48.md
      - Chapter 49: chapters/49.md
      - Chapter 50: chapters/50.md
      - Chapter 51: chapters/51.md
      - Chapter 52: chapters/52.md
      - Chapter 53: chapters/53.md
      - Chapter 54: chapters/54.md
      - Chapter 55: chapters/55.md
      - Chapter 56: chapters/56.md
      - Chapter 57: chapters/57.md
      - Chapter 58: chapters/58.md
      - Chapter 59: chapters/59.md
      - Chapter 60: chapters/60.md
      - Chapter 61: chapters/61.md
      - Chapter 62: chapters/62.md
      - Chapter 63: chapters/63.md
      - Chapter 64: chapters/64.md
      - Chapter 65: chapters/65.md
      - Chapter 66: chapters/66.md
      - Chapter 67: chapters/67.md
      - Chapter 68: chapters/68.md
      - Chapter 69: chapters/69.md
      - Chapter 70: chapters/70.md
      - Chapter 71: chapters/71.md
      - Chapter 72: chapters/72.md
      - Chapter 73: chapters/73.md
      - Chapter 74: chapters/74.md
      - Chapter 75: chapters/75.md
      - Chapter 76: chapters/76.md
      - Chapter 77: chapters/77.md
      - Chapter 78: chapters/78.md
      - Chapter 79: chapters/79.md
      - Chapter 80: chapters/80.md
      - Chapter 81: chapters/81.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/notegone/dao-de-jing

# Deployment Settings
deploy:
  provider: github
  repo: notegone/dao-de-jing
  branch: gh-pages

